name: Feature Request
description: Suggest a new feature for Exam Helper
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Add support for flashcard generation from documents
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem does this feature address?
      placeholder: Students need an easier way to create flashcards for spaced repetition study
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Add a "Generate Flashcards" button that creates Q&A pairs from the document
    validations:
      required: false
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there other ways to solve this problem?
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be useful
        - Important
        - Critical
    validations:
      required: false
